from components import page_metadata, page_footer
from dash import html, dcc
import pandas as pd
import plotly.express as px

from dashboard import df
# ================= MONTH ORDER FIX =================
month_order = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
               'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

df['Month_Name'] = pd.Categorical(df['Month_Name'], categories=month_order, ordered=True)
# ================= CHARTS =================

# 1️⃣ Doctor Workload Trend (Line) ✅ FIXED
trend = df.groupby(['Month_Name', 'Doctor_Name']).size().reset_index(name='Count')

fig1 = px.line(
    trend,
    x='Month_Name',   # ✅ FIX HERE
    y='Count',
    color='Doctor_Name',
    title="Doctor Workload Trend"
)

# 2️⃣ Doctor Performance (Bubble Scatter)
doc_perf = df.groupby('Doctor_Name')['patient_Id'].nunique().reset_index()
doc_perf.columns = ['Doctor_Name', 'Patient_Count']

fig2 = px.scatter(
    doc_perf,
    x='Doctor_Name',
    y='Patient_Count',
    size='Patient_Count',
    color='Patient_Count',
    title="Doctor Performance (Patient Volume)",
    size_max=40
)

# 3️⃣ Revenue by Doctor
rev = df.groupby('Doctor_Name')['payment_amount'].sum().reset_index()

fig3 = px.bar(
    rev,
    x='Doctor_Name',
    y='payment_amount',
    title="Revenue Generated by Doctors",
    color='payment_amount',
    color_continuous_scale="Blues"
)

# 4️⃣ No-Show Impact per Doctor
noshow = df.groupby('Doctor_Name')['No_Show_Flag'].sum().reset_index()

fig4 = px.bar(
    noshow,
    x='No_Show_Flag',
    y='Doctor_Name',
    orientation='h',
    title="No-Show Impact by Doctor",
    color='No_Show_Flag',
    color_continuous_scale="Reds"
)

# 5️⃣ Appointment Status Mix
status = df.groupby(['Doctor_Name', 'appointment_status']).size().reset_index(name='Count')

fig5 = px.sunburst(
    status,
    path=['Doctor_Name', 'appointment_status'],
    values='Count',
    title="Doctor Appointment Status Distribution"
)

# ================= LAYOUT =================
def doctor_layout():

    return html.Div([

        # NAVBAR
        html.Div([
            html.Div(className="nav-left"),
            html.Div("🏥 Multicare Hospital Analytics", className="nav-title"),
            html.Div([
                html.Span("👤 Admin", className="nav-user"),
                html.Button("Logout", id="logout-btn")
            ], className="nav-links")
        ], className="navbar"),

        # MAIN
        html.Div([

            # SIDEBAR
            html.Div([
                html.Img(
                    src="/assets/multicare2.png",
                    style={"width": "150px", "margin": "auto","margin-top":"1px", "display": "block"}
                ),
                html.H4("MULTICARE HOSPITAL", style={"textAlign": "center"}),
                html.Hr(),

                html.H3("Menu"),

                dcc.Link("🏠 Dashboard Overview", href="/dashboard", className="nav-item"),
                dcc.Link("📊 Appointment Analysis", href="/appointment", className="nav-item"),
                dcc.Link("🚫 No-Show Analysis", href="/noshow", className="nav-item"),
                dcc.Link("🔁 Patient Retention", href="/retention", className="nav-item"),
                dcc.Link("👨‍⚕️ Doctor Performance", href="/doctor", className="nav-item"),

                html.Hr(),

                html.H4("Filters"),

                dcc.Dropdown(
                    id="doc-month",
                    options=[{"label": m, "value": m} for m in month_order if m in df['Month_Name'].unique()],
                    placeholder="Select Month",
                    clearable=True
                ),

                dcc.Dropdown(
                    id="doc-year",
                    options=[{"label": y, "value": y} for y in sorted(df['Year'].dropna().unique())],
                    placeholder="Select Year",
                    clearable=True
                ),

                dcc.Dropdown(
                    id="doc-filter",
                    options=[{"label": d, "value": d} for d in df['Doctor_Name'].dropna().unique()],
                    placeholder="Select Doctor",
                    clearable=True
                ),

                dcc.Dropdown(
                    id="dept-filter",
                    options=[{"label": d, "value": d} for d in df['dept_Name'].dropna().unique()],
                    placeholder="Select Department",
                    clearable=True
                ),

            ], className="sidebar"),

            # CONTENT
            html.Div([

                html.H2("👨‍⚕️ Doctor Performance Analysis", className="section-title"),
                html.P("Evaluate doctor efficiency, workload, and patient handling performance",
                       className="section-subtitle"),

                html.Div(id="doc-kpi", className="kpi-container"),

                # ⚠️ KEEP WITHOUT figure (handled in callbacks)
                html.Div([
                    html.Div(dcc.Graph(id="doc-chart1"), className="chart-card"),
                    html.Div(dcc.Graph(id="doc-chart2"), className="chart-card"),
                ], className="charts"),

                html.Div([
                    html.Div(dcc.Graph(id="doc-chart3"), className="chart-card"),
                    html.Div(dcc.Graph(id="doc-chart4"), className="chart-card"),
                ], className="charts"),

                html.Div([
                    html.Div(dcc.Graph(id="doc-chart5"), className="chart-card"),
                ], className="charts"),
                page_metadata(),
                page_footer(),

            ], className="content")

        ], className="main")

    ])